name: Docker Image CI

on:
  push:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  pull_request:
    branches: [ "*" ]
    # Build semver tags as releases.
    tags: [ '*.*' ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
